### ISSUE TITLE
Unable to add the questions automatically to the quiz

### ISSUE THREAD

**Issue by manzoorwanijk** [savsofts/savsoftquiz_v3.0#3]
Hi,
I started using this package just 3 days ago. There is some bug or something wrong at least.
When I create a new Quiz and set the option **How do you want to add questions into this quiz?**  to **Automatically**, Then on the next page I can only see the category list and level list, NOT the number of questions.

**Comment by savsofts** [comment]
Hi,

There is no bug. You can check its working in our online demo.
You can buy our support service, our experts will fix it.

Thanks

**Comment by manzoorwanijk** [comment]
Fixed it, thank you
